### ISSUE TITLE
no such file or directory, open 'scratchpad/allRepeaters_1610227284486.json

### ISSUE THREAD

**Issue by kipz** [m7xer/handy#1]
On Linux (Ubuntu 20.04)...

```
$ ./scripts/generateChirpCSV IO81ql
#####
UK Maidenhead locator required for best results! for example:
./scripts/generateChirpCSV IO92BL
home location calculated from IO81QL as {"lat":51.458333333333336,"lon":-2.666666666666667}
allRepeaters 622
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'scratchpad/allRepeaters_1610227284486.json'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at save (/home/kipz/scm/kipz/handy/scripts/generateChirpCSV:62:5)
    at /home/kipz/scm/kipz/handy/scripts/generateChirpCSV:190:3
    at Request._callback (/home/kipz/scm/kipz/handy/scripts/generateChirpCSV:90:10)
    at Request.self.callback (/home/kipz/scm/kipz/handy/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/kipz/scm/kipz/handy/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/kipz/scm/kipz/handy/node_modules/request/request.js:1076:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'scratchpad/allRepeaters_1610227284486.json'
}
```

**Comment by kipz** [comment]
Once `scratchpad` is created manually, all works as expected.

**Comment by m7xer** [comment]
Fix committed, using `mkdirp.sync` fixes this for linux.
